### ISSUE TITLE
Homework Assignment Week 2: Putting it All Together

### ISSUE THREAD

**Issue by katesteinmeyer** [katesteinmeyer/katesteinmeyer.github.io#2]
@DiyahM 
@Keenahn
@LijieZhou

Time to complete assignment: 45 minutes.

*Main requirements for this assignment can be found in "homework-week-2-contact-form.html",  "homework-week-2.html" and "hw-week2.css" files.

This is a work in progress! I didn't get much time to do the CSS for the form. 

Cheers,
Kate

Attached screenshot.
<img width="1073" alt="screen shot 2015-08-24 at 4 41 48 pm" src="https://cloud.githubusercontent.com/assets/3793880/9455322/d8bdca30-4a7e-11e5-9b26-579e3d6bf722.png">

**Comment by DiyahM** [comment]
Hi @katesteinmeyer 

Congrats on this week's progress. I see this is a work in progress. Here are some tips as we move forward:

1) Consider making the design of the site align with an actual portfolio site instead of a homework site. Each week you can find ways to incorporate the assignments into the site instead of creating new homework pages.
2) Make your contact form functional by adding a url and method to your form tag. Review Week 2's lecture for tips. In addition, formspree.io gives a great example for use.

Let me know if you have any additional questions.
-Diyah

**Comment by katesteinmeyer** [comment]
Thanks @DiyahM I made the changes.
